### ISSUE TITLE
Parsing units when there are multiple units

### ISSUE THREAD

**Issue by davidtheclark** [TrySound/postcss-value-parser#11]
I'm pretty this API doesn't account for a declaration like `margin: 1px 2rem 3em`, where there are multiple units. Right now it looks like I'm getting `px 2rem 3em` as the unit on that value.

**Comment by TrySound** [comment]
You are get this tree. For every `word` you can call valueParser.unit(node.value); which will return `{ number: '.4s', unit: 'px' }`
```js
{ nodes:
   [ { type: 'word', value: '1px' },
     { type: 'space', value: ' ' },
     { type: 'word', value: '2rem' },
     { type: 'space', value: ' ' },
     { type: 'word', value: '3em' } ] }
```

**Comment by TrySound** [comment]
@davidtheclark Oh, do you use unit on whole value?

**Comment by davidtheclark** [comment]
Thanks for the clarification. I think it's worth mentioning in the README that `.unit()` should be called on the `value` of `'word'` nodes, because I'm sure other users would try the same thing I tried and be confused.
