### ISSUE TITLE
Get index of node within source string

### ISSUE THREAD

**Issue by jeddy3** [TrySound/postcss-value-parser#12]
Would it be possible to support getting the string-index of a node within its source string? Similar to how `postcss-selector-parser` [does it](https://github.com/postcss/postcss-selector-parser/blob/master/API.md#nodesourceindex).

The use-case is for stylelint, to feed these indexes into PostCSS 5's new warning index option, in order to get accurate positions for errors.

**Comment by TrySound** [comment]
@jeddy3 Do you mean position start?

**Comment by jeddy3** [comment]
Yep. I think so.

So given a value of:

```css
red, rgba(0, 0, 0, 0);
```

You'll get something like 

```js
nodes: [
      type: 'function',
      value: 'rgba',
      before: "",
      after: "",
      sourceIndex: 5 // the start position of the `rgba` in the original value string
```

Although, now I'm wondering if I misunderstood our needs. I'm going to ask for @davidtheclark advice on this.

@davidtheclark I'm working on `function-blacklist` at the moment and I believe I need to get the start position of the offending function name to pass into `report()`. 

So given

```css
a {
  background-image: 
    linear-gradient(45deg, blue, red),
    linear-gradient(90deg, black, white);
}
```

Am I right in thinking I'm after the start position of the two function names within the value string? And this is something we're hoping to get from the value parser?

**Comment by davidtheclark** [comment]
Yes, @jeddy3: That link to the [postcss-selector-parser feature](https://github.com/postcss/postcss-selector-parser/blob/master/API.md#nodesourceindex) is dead on: that's what we need for a completely accurate position.

**Comment by jeddy3** [comment]
Thanks for the clarification @davidtheclark .

@TrySound Do you think it'll be possible?

**Comment by TrySound** [comment]
@jeddy3 Yep, I'll do that.

**Comment by jeddy3** [comment]
Thank you :)

**Comment by TrySound** [comment]
@jeddy3  @davidtheclark Do you expect sourceIndex in div since space before or div char?
`word , ` -> `sourceIndex: 5`
`word , ` -> `sourceIndex: 4`

**Comment by jeddy3** [comment]
That's a good question. I've not used the `postcss-selector-parser` API yet, so I'm going to ping @ben-eb to ask which of these two behaviours would be most consistent with what is in `postcss-selector-parser`?

**Comment by ben-eb** [comment]
Since `sourceIndex` is relative to the *original string*, whitespace must be taken into account for the position to be accurate. So for `word ,` the comma would be `sourceIndex: 5`.

**Comment by TrySound** [comment]
@ben-eb You mean 4? :)

**Comment by ben-eb** [comment]
`sourceIndex` should be zero based. :smile:

**Comment by TrySound** [comment]
@ben-eb  posDiv - before.length ?

**Comment by ben-eb** [comment]
Whoops. I meant 4. :smile:

**Comment by jeddy3** [comment]
@ben-eb Thanks for the popping by to answer the question :)

@TrySound Thanks again for getting this done, and so quickly too :)

**Comment by davidtheclark** [comment]
Wait ... in the `word ,`, the index of `,` *should* be 5 --- I don't understand why you both settled on 4. `'word ,'.indexOf(',') === 5`

**Comment by davidtheclark** [comment]
Nevertheless ... I reviewed a bunch of the tests in the PR https://github.com/TrySound/postcss-value-parser/pull/17/files and they all made sense/seemed right to me, so maybe I'm just missing something here.

**Comment by TrySound** [comment]
@davidtheclark It takes also the space before which is start of the node
```js
{ type: 'div', sourceIndex: 4, value: ',', before: ' ', after: '' }
```

**Comment by davidtheclark** [comment]
+1
