### ISSUE TITLE
Walk immediate children `each`

### ISSUE THREAD

**Issue by MadLittleMods** [TrySound/postcss-value-parser#13]
Similar to the [`container.each(callback)`](https://github.com/postcss/postcss/blob/master/docs/api.md#containereachcallback) in the PostCSS API, it would be useful to iterate only the immediate children of a value.

Perhaps this use-case can be solved with the [`bubble` parameter](https://github.com/TrySound/postcss-value-parser#valueparserwalknodes-cb-bubble).

I would use this for acting only on the top-level functions.

---

For now you can iterate over the `nodes` array:

```js
let parsedValue = valueParser(decl.value);
parsedValue.nodes.forEach((topLevelValueNode) => {});
```

**Comment by MadLittleMods** [comment]
It looks like you can do this using the `bubble` parameter and some boilerplate:

```
valueParser.walk(someNode, () => { /* do stuff */ return false;}, false);
```

**Comment by TrySound** [comment]
@MadLittleMods Bubble just iterate all nodes of the function since deepest node. It not prevent nodes iteration. For this you can `return false` in callback.

**Comment by MadLittleMods** [comment]
@TrySound Ahhh the docs were not very clear to me about this. I made a PR to try to clarify this area: https://github.com/TrySound/postcss-value-parser/pull/18
