### ISSUE TITLE
Add `clone(node)`

### ISSUE THREAD

**Issue by MadLittleMods** [TrySound/postcss-value-parser#16]
Add `valueParser.clone(node)` similar to the [`node.clone` in the PostCSS API](https://github.com/postcss/postcss/blob/master/docs/api.md#nodecloneprops).

My use case is so I can duplicate and modify nodes.

**Comment by TrySound** [comment]
@MadLittleMods You can use object assign, it's just plain objects.

**Comment by TrySound** [comment]
@MadLittleMods Or https://www.npmjs.com/package/extend

**Comment by TrySound** [comment]
@MadLittleMods Or https://github.com/sindresorhus/deep-assign

**Comment by MadLittleMods** [comment]
Or [`object-assign`](https://www.npmjs.com/package/object-assign) :stuck_out_tongue_winking_eye: 

But I would need to use a deep clone because it is a deeply nested structure to get true separation. Having a nice utility `clone` could really ease the pain.

**Comment by TrySound** [comment]
@MadLittleMods What's the problem? It's just ast without any aux props.

**Comment by MadLittleMods** [comment]
@TrySound I understand keeping the API light. 

Because it is just a normal object, it has the same `Object.assign`/`extend` problems without the `deep` boolean which not every solution has (right tool for the job though).
