### ISSUE TITLE
Semicolons Erroneously Part of Value

### ISSUE THREAD

**Issue by shellscape** [TrySound/postcss-value-parser#27]
I've found a case where a semicolon is being included in a `word` value.

Consider the following input: `url(test.png) no-repeat #AABBC;`

And the resulting output:

```js
ValueParser {
  nodes: 
   [ { type: 'function',
       sourceIndex: 0,
       value: 'url',
       before: '',
       nodes: [Object],
       after: '' },
     { type: 'space', sourceIndex: 13, value: ' ' },
     { type: 'word', sourceIndex: 14, value: 'no-repeat' },
     { type: 'space', sourceIndex: 23, value: ' ' },
     { type: 'word', sourceIndex: 24, value: '#AABBC;' } ] }
```

`value: '#AABBC;' ` should not include a semicolon, rather that should probably be part of an `after` property.

**Comment by TrySound** [comment]
@shellscape postcss does not include semicolon in value. So don't see the problem.

**Comment by shellscape** [comment]
ouch, closed before a chance for discussion. please be more patient :)

while I'm sure that the majority of use for this module will be within a postcss stack, it's also viable for use outside of postcss, and actually very useful! wouldn't a small check for this be useful in that situation?
