### ISSUE TITLE
Issue with displaying raw output in console

### ISSUE THREAD

**Issue by alibby251** [TrySound/postcss-value-parser#28]
I've been experimenting with the postcss-value-parser plugin as part of an upcoming project, but unfortunately have a bit of a problem.

I've tried running the rgba() example given on the front page of this site - in my case, I've used a Gulp task:
```
'use strict';
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var valueParser = require('postcss-value-parser');

gulp.task('default', function () {
	var cssBackgroundValue = 'rgba(233, 45, 66, .5)';
	var parsedValue = valueParser(cssBackgroundValue);
	console.log(parsedValue);
});
```
The plugin version is the latest available when installing it using npm. The aim here is to simply see the full node tree, so I can replicate what you've shown on your site.

The odd thing here though is that the output I see doesn't entirely match what I've seen on the front page of your site; I'm guessing that the console.log statement isn't referencing the right value. I'm sure I'm doing something wrong, but am not sure what - any chance you could please put me right? ;-)
![issue](https://cloud.githubusercontent.com/assets/802739/14219909/c48eac80-f854-11e5-892c-2c7e47453790.png)
As a suggestion, it might be worth adding something to make it clearer as to how you are displaying the results of parsing the RGBA color, rather than just the results? 

Thanks!

**Comment by ben-eb** [comment]
Try using node's inspect method, the default log truncates object references.

```js
console.log(require('util').inspect(parsedValue, false, null));
```

**Comment by alibby251** [comment]
This is perfect - thanks @ben-eb!
