### ISSUE TITLE
Invalid parsing `calc` function containing multiplication

### ISSUE THREAD

**Issue by evilebottnawi** [TrySound/postcss-value-parser#33]
```css
/* Valid CSS */
a { top: calc(10px*2); }
```
Return:
```shell
{ type: 'function',
      sourceIndex: 0,
      value: 'calc',
      before: '',
      after: '',
      nodes: [ { type: 'word', sourceIndex: 5, value: '10px*2' } ] }
```
Weird value of `value` property.

Original issue with information https://github.com/stylelint/stylelint/issues/2551#issuecomment-299666591

**Comment by TrySound** [comment]
@evilebottnawi value-parser has no special cases about calc. You get splitted value only with space or divider. Nothing weird.

**Comment by evilebottnawi** [comment]
@TrySound i.e best solution do this in `stylelint`?

**Comment by TrySound** [comment]
Yep.

**Comment by TrySound** [comment]
Not so difficult. Just reduce array with calc nodes.

**Comment by diervo** [comment]
Oops, I did the PR and then I saw this issue :)

Per [spec](https://drafts.csswg.org/css-values-3/#calc-syntax) spaces are not required for both multiplication and division operations, hence the PR!
