### ISSUE TITLE
valueParser.unit(quantity) and scientific numbers

### ISSUE THREAD

**Issue by jeddy3** [TrySound/postcss-value-parser#37]
Firstly, thanks for writing this parser! We use it extensively in stylelint and its been rock solid so far.

[We use](https://github.com/stylelint/stylelint/blob/master/lib/utils/getUnitFromValueNode.js#L35) `valueParser.unit(quantity)` in our `unit-no-unknown` rule.

An issue, https://github.com/stylelint/stylelint/issues/3537, was raised about support for scientific numbers (e.g. `4e2px`) as covered [in the specs](https://www.w3.org/TR/css-syntax/#consume-a-number).

Reproduce with:

```js
var postcssValueParser = require("postcss-value-parser");
postcssValueParser.unit("1e5px")
```

Expected:

```js
{
  number: "1e5",
  unit: "px"
}
```

Got:

Expected:

```js
{
  number: "1",
  unit: "e5px"
}
```

Is this something you'll be willing to support in this value parser?

**Comment by TrySound** [comment]
@jeddy3 hi, I'm not actively working on this project. I can accept PR with the fix.
