### ISSUE TITLE
Values starting with letter 'e' and a digit

### ISSUE THREAD

**Issue by PEsteves8** [TrySound/postcss-value-parser#48]
Hi,

In situations in which the value is a string starting with the letter 'e' followed by a digit, the parser will assume that the string starts with a numeric value and parses it accordingly resulting in a string looking like 'NaNrestofstring'.

We got this when the parser was processing animation names that were hashed.

You can easily reproduce this issue by adding the following test:

```
 {
    fixture: "e06d4a",
    expected: false
 }
``` 

The result will instead be 'NaN6d4a'.

I'll happily submit a PR to fix this.

Thanks

**Comment by evilebottnawi** [comment]
PR welcome
