### ISSUE TITLE
Values parser should not use PostCSS core classes

### ISSUE THREAD

**Issue by ai** [TrySound/postcss-value-parser#60]
Every parser is unique. I understand that you want to reduce your code and have similar PostCSS’s `append()`, etc API. But in addition to simple functions like `append`, PostCSS classes have a lot of internal hacks.

By extending PostCSS’s classes you can start to use private API, which can change in patch releases.

For instance, it happens with PostCSS 7.0.20 fix https://github.com/postcss/postcss/issues/1305

I recommend just copy-paste PostCSS functions in your own classes. It is OK for cases, where you have AST for different things.

**Comment by ai** [comment]
I reverted 7.0.19 because it breaks your code, but in the next 8.0 it will be a policy, that “extending PostCSS classes” is a private API and I will not revert changes if something will be broken.

(Sorry, for “Russian style” in commet, I am reverting the release instead of sleep)

**Comment by evilebottnawi** [comment]
@ai I think you report to invalid repo, I can't see there we extends PostCSS nodes, maybe you mean `postcss-values-parser` https://github.com/shellscape/postcss-values-parser?

**Comment by ai** [comment]
Oops, sorry
