### ISSUE TITLE
README.md typo: functon => function

### ISSUE THREAD

**Issue by jonathantneal** [TrySound/postcss-value-parser#7]
Line 46.

I copied the example and spent several confused seconds. I want my money back. Oh wait... :smile: 

Works flawlessly once the typo is fixed. Awesome work!

**Comment by TrySound** [comment]
Thanks, Jonathan!
Fixed with https://github.com/TrySound/postcss-value-parser/commit/5bfd0c4244a75fddfc266b601e977ffc65180785
